### ISSUE TITLE
enable-appindicator, enable-flatpak bug

### ISSUE THREAD

**Issue by legeekmetalleux** [tommytran732/pamac-flatpak-gnome#2]
Build started at 2022-02-06T16:17:34.468105
Main binary: /usr/bin/python
Build Options: -Denable-flatpak=true -Denable-appindicator=true -Denable-fake-gnome-software=true -Dprefix=/usr -Dsysconfdir=/etc -Dbuildtype=release
Python system: Linux
The Meson build system
Version: 0.61.1
Source dir: /home/max/.cache/yay/pamac-flatpak-gnome/src/pamac-v10.2.0
Build dir: /home/max/.cache/yay/pamac-flatpak-gnome/src/pamac-v10.2.0/builddir
Build type: native build

../meson.build:1:0: ERROR: Unknown options: "enable-appindicator, enable-flatpak"

**Comment by tommytran732** [comment]
Should be fixed.
